site_name: ARC Docs
#site_url:
site_description: Academic and Research Computing at Portland State University
#site_author:
#site_favicon:

repo_url: https://github.com/PSU-OIT-ARC/arc-docs/tree/master/docs

pages:
- ['index.md', 'Introduction']
#- ['user-guide.md', 'User Guide']
- ['about.md', 'About']

#theme: readthedocs