site_name: ARC
#site_url:
site_description: Academic and Research Computing at Portland State University

repo_url: https://github.com/PSU-OIT-ARC/arc-docs

pages:
- [index.md, Home]
- [about.md, About]

theme: readthedocs